### ISSUE TITLE
对于 ZHIHUI 算法的概率存有一些疑惑

### ISSUE THREAD

**Issue by kallydev** [david-pzh/BilibiliLottery#2]
ZHIHUI 这个算法的思路实在是太有趣了，但在分析后我有一些疑虑

> 当然由于 2 的 256 次方是一个巨大的数字，有很大概率是会出现没有任何一个用户的奖券号码跟开奖号码是一致的，所以我会在所有的参与抽奖用户里面，选取彩票券与这个数字最接近的一个用户，作为获奖者送出奖品

### 1. 看似随机，但每个用户的中奖概率是不等的

已求出用户 A ([35040733](https://space.bilibili.com/35040733)) 和 B ([20259914](https://space.bilibili.com/20259914)) 的 UID Hash 分别为

```text
787ccebcc8a084b1df6994047be31706ebebb520ba0ce53dc44ec49c24eadcbb
4b3ec795e99f163d022978866fb89110b9e74c1d1aa5932f074e441d115d4cda
```

再把 Hash 的 16 进制编码转换为 10 进制分别为 

```text
54498057715370390290478912473173450895822179519350824269452220845244860259515
34034385650919512184593039349216595979306765265358617344517855224905181514970
```

将 16 进制转换为 10 进制的代码是这样的

```python
int('787ccebcc8a084b1df6994047be31706ebebb520ba0ce53dc44ec49c24eadcbb', 16)
int('4b3ec795e99f163d022978866fb89110b9e74c1d1aa5932f074e441d115d4cda', 16)
```

SHA 256 的范围为从 `[0, ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff]`，总共有 `115792089237316195423570985008687907853269984665640564039457584007913129639935` 种可能性，从中求用户 A 和 B 的差值的一半 `abs(a - b) / 2` 结果为

```text
10231836032225439052942936561978427458257707126996103462467182810169839372273
```

通过以上结果对 A 和 B 分别进行加减后的中奖范围如下

```text
[44266221683144951237535975911195023437564472392354720806985038035075020887242, 115792089237316195423570985008687907853269984665640564039457584007913129639935]
[0, 44266221683144951237535975911195023437564472392354720806985038035075020887243]
```

用户 A 的中奖结果有 `71525867554171244186035009097492884415705512273285843232472545972838108752693` 种，而用户 B 的中奖结果有 `44266221683144951237535975911195023437564472392354720806985038035075020887243` 种。通过比较 A 和 B 的中奖范围可以发现 A 比 B 中奖的结果多出 **`27259645871026292948499033186297860978141039880931122425487507937763087865450`** 种

### 2. 如果最后获奖 Hash 与两个用户的 Hash 距离相等，或者距离为单数无法等分，应该如何解决这种情况？

递归或许能够解决，就像 Bogosort 也有可能是一万年

:dog: :dog: :dog:

**Comment by kallydev** [comment]
@cjyx9 看到点了 confused，方便说下哪里有问题么

**Comment by baby5** [comment]
加上"最接近的"让概率不均等了

**Comment by kallydev** [comment]
> 加上"最接近的"让概率不均等了

是的，问题出在这一步
